language: java
jdk:
- openjdk7

env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
  - PROJECT_ID=plasma-cascade-621
  - SRV_ACCOUNT=318301250744-gg9klbthoi4069jl0nudifnd50j4bsim@developer.gserviceaccount.com

before_install:
- sudo pip install PyOpenSSL
- openssl aes-256-cbc -K $encrypted_e7fb07691267_key -iv $encrypted_e7fb07691267_iv
  -in $PROJECT_ID.p12.enc -out $PROJECT_ID.p12 -d
- curl https://sdk.cloud.google.com | bash
- $HOME/google-cloud-sdk/bin/gcloud components update app -q
- $HOME/google-cloud-sdk/bin/gcloud config set project $PROJECT_ID
- $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account $SRV_ACCOUNT --key-file $PROJECT_ID.p12

script:
- mvn package
- $HOME/google-cloud-sdk/bin/gcloud preview app deploy --version staging target/cd-on-paas
- mvn -Dtest=**/*AcceptanceTest.java -DbaseUrl="https://staging-dot-$PROJECT_ID.appspot.com/" test

after_success:
- $HOME/google-cloud-sdk/bin/gcloud preview app deploy --version prod target/cd-on-paas

