language: java
jdk:
  - openjdk7

env:
  global:
    secure: getgF3hG/K+wWV+ff8lXsmYm4PPt536O8Hcsx180BitKRh7OOih7gRc5yywXFEJPe8+COfZ2YvAUMvQrUVmlY/lP/vTLfSxZGzWTxeD2z+dM7hDb2FxnMP9bk91gdN9l8HbEBT3Z5iYpu2XDeb4hFrdnaiw601eO2jqOatek7tU=

before_install:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - gem install dpl

script:
  - mvn test
  - dpl --provider=heroku --api-key=`heroku auth:token` --app=cd-on-paas-testing
  - mvn -Dtest=**/*AcceptanceTest.java -DbaseUrl='https://cd-on-paas-testing.herokuapp.com/' test

after_success:
  - dpl --provider=heroku --api-key=`heroku auth:token` --app=cd-on-paas
